name: spello_frontend
description: "Spello"

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
version: 1.0.0+1

environment:
  sdk: ^3.6.0

# Dependencies specify other packages that your package needs in order to work.
dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  animated_toggle_switch: ^0.8.4
  smooth_page_indicator: ^1.2.0+3
  flutter_slidable: ^4.0.0
  fl_chart: ^0.70.2
  tutorial_coach_mark: ^1.2.13
  shared_preferences: ^2.5.2
  lottie: ^3.3.1
  http: ^1.3.0
  permission_handler: ^11.0.1
  record: ^5.2.1
  path_provider: ^2.1.5
  path: 1.9.1
  audioplayers: ^6.2.0
  provider: ^6.0.5
  shelf_router: ^1.1.4
  shelf: ^1.4.2
  shelf_multipart: ^2.0.1
  http_parser: ^4.1.2




  # Added animated toggle switch dependency

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.14.3"
  flutter_lints: ^5.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/spellologo.png"
  remove_alpha_ios: true

    
  #should in line 20, not sure

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices.
  

flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:

    - assets/images/parental_control_two.png
    - assets/images/clipboard.png
    - assets/images/onboarding_screen_one.png
    - assets/images/onboarding_screen_two.png
    - assets/images/onboarding_screen_three.png
    - assets/images/cloud.png
    - assets/images/parental_control.png
    - assets/images/start.png
    - assets/images/help_center.png
    - assets/images/settings.png
    - assets/images/dashboard.png
    - assets/images/notification.png
    - assets/images/parental_control_one.png
    - assets/images/game_one.png
    - assets/images/game_two.png
    - assets/images/game_three.png
    - assets/images/apple.png
    - assets/images/astronaut.png
    - assets/images/facebook.jpg
    - assets/images/fb.png
    - assets/images/google.png
    - assets/images/spello.png
    - assets/images/page_under_construction.png
    - assets/images/under_construction.png
    - assets/animations/Confetti.json
    - assets/animations/UFO.json
    - assets/images/bg1.jpg
    - assets/images/login.png
    - assets/images/spellologo.png
    - assets/images/character.png
    - assets/images/ufo.png
    - assets/images/emtyheart.png
    - assets/images/heart.png
    - assets/images/b1.jpg
    - assets/images/b2.jpg
    - assets/images/b3.jpg
    - assets/images/b4.jpg
    - assets/images/b5.jpg
    - assets/images/b6.jpg
    - assets/images/b7.png
    - assets/images/b8.png
    - assets/images/b9.png
    - assets/images/b10.png
    - assets/images/b11.png
    - assets/images/b12.png
    - assets/images/UFO.json
    - assets/images/alien1.png
    - assets/images/alien2.png
    - assets/images/alien3.png
    - assets/images/alien4.png
    - assets/images/alien5.png
    - assets/images/alien6.png
    - assets/images/alien7.png
    - assets/images/newb1.png
    - assets/images/newb2.png
    - assets/images/profile_picture.png
    - assets/images/hangman.png


  fonts:
    - family: "Fredoka One"
      fonts:
        - asset: assets/fonts/FredokaOne-Regular.ttf

    - family: "Fredoka"
      fonts:
        - asset: assets/fonts/Fredoka.ttf



  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section.
  # fonts:
  #   - family: CustomFont
  #     fonts:
  #       - asset: fonts/CustomFont-Regular.ttf
  #       - asset: fonts/CustomFont-Bold.ttf
  #         weight: 700