name: hangman
description: Simple flutter hangman
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 0.1.0

environment:
  sdk: ">=2.12.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - data_repo/img/progress_0.png
    - data_repo/img/progress_1.png
    - data_repo/img/progress_2.png
    - data_repo/img/progress_3.png
    - data_repo/img/progress_4.png
    - data_repo/img/progress_5.png
    - data_repo/img/progress_6.png
    - data_repo/img/progress_7.png
    - data_repo/img/victory.png
